;;;;
;;;; File generated by cpct_aks2c CPCtelera script
;;;; Souce file of this conversion: assets/music/Instrument.aks
;;;; Generation time: sáb 28 ene 2023 11:49:57 CET
;;;;

;;;; Song 'instrument' metadata constants
instrument_address = 0x02E5
instrument_size    = 78
instrument_end     = 0x332

;;;; Song 'instrument' declaration
.globl _instrument
