;;;;
;;;; File generated by cpct_aks2c CPCtelera script
;;;; Souce file of this conversion: assets/music/Musica.aks
;;;; Generation time: sáb 28 ene 2023 11:49:59 CET
;;;;

;;;; Song 'musica' metadata constants
musica_address = 0x0250
musica_size    = 149
musica_end     = 0x2e4

;;;; Song 'musica' declaration
.globl _musica
