// File generated by CONVERT_PALETTE macro from CPCtelera
// Converted firmware palette declaration
// 
#ifndef _global_pal_H_
#define _global_pal_H_

#include <types.h>

extern const u8 global_pal[16];

#endif
